### ISSUE TITLE
TModLoader 64 Bit Compatibility? Mod Crashes Using 64 Bit

### ISSUE THREAD

**Issue by kjopnfer** [kjopnfer/OvermorrowMod#34]
Apparently the mod crashes the game when loading in. It isn't instantaneous when loading a world but it apparently happens very quickly. 

[Screenshot of the error](https://media.discordapp.net/attachments/844066563975544894/936292570147991623/Terraria__Error_tModLoader_v0.11.8.5_1_28_2022_12_11_25_AM.png)

**Comment by einarmo** [comment]
I highly doubt this has anything to do with 64 bit. I'll take a look.

**Comment by einarmo** [comment]
Uh, never mind. 64 bit tmodloader is apparently unofficial. Is this really worth spending a lot of time on?
